In [21]:
# upload dataset
# Group1: https://www.kaggle.com/datasets/mohithsairamreddy/salary-data
# Group2: https://www.kaggle.com/datasets/jaderz/hospital-beds-management?select=services_weekly.csv
# Group3: https://www.kaggle.com/datasets/hmavrodiev/london-bike-sharing-dataset
# Group4: https://www.kaggle.com/datasets/jocelyndumlao/inclusive-economics-growth-determinants
# Group5: https://www.kaggle.com/datasets/kbrakssa/students-grading-dataset

In [22]:
# Data handling
import pandas as pd
import numpy as np

# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Statistical testing
from scipy import stats

In [23]:
from pathlib import Path

# Path to your CSV file
file_path = Path("data") / "Students_Grading_Dataset.csv"

# Load CSV into a pandas DataFrame
df = pd.read_csv(file_path)

# Check first 5 rows
df.head()

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,...,Projects_Score,Total_Score,Grade,Study_Hours_per_Week,Extracurricular_Activities,Internet_Access_at_Home,Parent_Education_Level,Family_Income_Level,Stress_Level (1-10),Sleep_Hours_per_Night
0,S1000,Omar,Williams,student0@university.com,Female,22,Engineering,52.29,55.03,57.82,...,85.90,56.09,F,6.2,No,Yes,High School,Medium,5,4.7
1,S1001,Maria,Brown,student1@university.com,Male,18,Engineering,97.27,97.23,45.80,...,55.65,50.64,A,19.0,No,Yes,NaN,Medium,4,9.0
2,S1002,Ahmed,Jones,student2@university.com,Male,24,Business,57.19,67.05,93.68,...,73.79,70.30,D,20.7,No,Yes,Master's,Low,6,6.2
3,S1003,Omar,Williams,student3@university.com,Female,24,Mathematics,95.15,47.79,80.63,...,92.12,61.63,A,24.8,Yes,Yes,High School,High,3,6.7
4,S1004,John,Smith,student4@university.com,Female,23,CS,54.18,46.59,78.89,...,68.42,66.13,F,15.4,Yes,Yes,High School,High,2,7.1

In [24]:
# Exercise 1
# Group1: Test whether there is a significant difference in the average salary between two groups (e.g., Group A and Group B).
# Group2: Testing Whether Events (like"flu") Significantly Impact Staff Morale
# Group3: weekend has an effect on the number of electric cycles rented (cnt)
# Group4: Test whether there is a significant difference in the grdp_capita of province A(ACEH) and province B(BALI)
# Group5: Does High Stress Lead to Lower Performance?
# Identify H_o and H_1

In [25]:
# Exercise 2
# Data cleanig 

# remove unused columns
df = df.drop(columns=['Student_ID', 'First_Name', 'Last_Name', 'Email'])

# Numerical columns
numerical_cols = df.select_dtypes(include=['number']).columns
print("Numerical columns:", numerical_cols)

# Categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns
print("Categorical columns:", categorical_cols)

Numerical columns: Index(['Age', 'Attendance (%)', 'Midterm_Score', 'Final_Score',
       'Assignments_Avg', 'Quizzes_Avg', 'Participation_Score',
       'Projects_Score', 'Total_Score', 'Study_Hours_per_Week',
       'Stress_Level (1-10)', 'Sleep_Hours_per_Night'],
      dtype='str')
Categorical columns: Index(['Gender', 'Department', 'Grade', 'Extracurricular_Activities',
       'Internet_Access_at_Home', 'Parent_Education_Level',
       'Family_Income_Level'],
      dtype='str')

C:\Users\Chhenghab\AppData\Local\Temp\ipykernel_23724\3189615325.py:12: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=['object']).columns

In [26]:
#handling missing values
# Check for missing values
missing_values = df.isnull().sum()
print("Missing values in each column:\n", missing_values)

missing_values_percent = (df.isnull().sum() / len(df)) * 100
print("Percentage of missing values in each column:\n", missing_values_percent)

df.drop_duplicates()

Missing values in each column:
 Gender                           0
Age                              0
Department                       0
Attendance (%)                 516
Midterm_Score                    0
Final_Score                      0
Assignments_Avg                517
Quizzes_Avg                      0
Participation_Score              0
Projects_Score                   0
Total_Score                      0
Grade                            0
Study_Hours_per_Week             0
Extracurricular_Activities       0
Internet_Access_at_Home          0
Parent_Education_Level        1794
Family_Income_Level              0
Stress_Level (1-10)              0
Sleep_Hours_per_Night            0
dtype: int64
Percentage of missing values in each column:
 Gender                         0.00
Age                            0.00
Department                     0.00
Attendance (%)                10.32
Midterm_Score                  0.00
Final_Score                    0.00
Assignments_Avg               10.34
Quizzes_Avg                    0.00
Participation_Score            0.00
Projects_Score                 0.00
Total_Score                    0.00
Grade                          0.00
Study_Hours_per_Week           0.00
Extracurricular_Activities     0.00
Internet_Access_at_Home        0.00
Parent_Education_Level        35.88
Family_Income_Level            0.00
Stress_Level (1-10)            0.00
Sleep_Hours_per_Night          0.00
dtype: float64

,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Total_Score,Grade,Study_Hours_per_Week,Extracurricular_Activities,Internet_Access_at_Home,Parent_Education_Level,Family_Income_Level,Stress_Level (1-10),Sleep_Hours_per_Night
0,Female,22,Engineering,52.29,55.03,57.82,84.22,74.06,3.99,85.90,56.09,F,6.2,No,Yes,High School,Medium,5,4.7
1,Male,18,Engineering,97.27,97.23,45.80,NaN,94.24,8.32,55.65,50.64,A,19.0,No,Yes,NaN,Medium,4,9.0
2,Male,24,Business,57.19,67.05,93.68,67.70,85.70,5.05,73.79,70.30,D,20.7,No,Yes,Master's,Low,6,6.2
3,Female,24,Mathematics,95.15,47.79,80.63,66.06,93.51,6.54,92.12,61.63,A,24.8,Yes,Yes,High School,High,3,6.7
4,Female,23,CS,54.18,46.59,78.89,96.85,83.70,5.97,68.42,66.13,F,15.4,Yes,Yes,High School,High,2,7.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Male,19,Business,NaN,82.15,60.33,80.09,99.32,5.00,58.42,85.21,D,25.5,No,Yes,High School,Low,10,8.3
4996,Male,19,Business,65.11,86.31,49.80,NaN,88.08,2.79,60.87,95.96,C,5.0,No,Yes,NaN,Medium,4,4.0
4997,Female,24,CS,87.54,63.55,64.21,94.28,50.19,3.13,82.65,54.25,A,24.8,Yes,No,High School,Medium,4,6.3
4998,Male,23,CS,92.56,79.79,94.28,81.20,61.18,0.40,94.29,55.84,A,16.1,Yes,Yes,Bachelor's,Low,1,8.4
4999,Female,21,Engineering,83.92,83.24,53.47,51.76,83.51,0.49,69.25,77.86,F,29.2,No,Yes,PhD,Low,2,6.1

In [27]:
#fill missing values
df["Attendance (%)"].fillna(df["Attendance (%)"].mean(), inplace=True)
df["Assignments_Avg"].fillna(df["Assignments_Avg"].mean(), inplace=True)
df["Parent_Education_Level"].fillna("Unknown", inplace=True)

C:\Users\Chhenghab\AppData\Local\Temp\ipykernel_23724\1710250459.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Attendance (%)"].fillna(df["Attendance (%)"].mean(), inplace=True)
C:\Users\Chhenghab\AppData\Local\Temp\ipykernel_23724\1710250459.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Assignments_Avg"].fillna(df["Assignments_Avg"].mean(), inplace=True)
C:\Users\Chhenghab\AppData\Local\Temp\ipykernel_23724\1710250459.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Parent_Education_Level"].fillna("Unknown", inplace=True)

0       High School
1           Unknown
2          Master's
3       High School
4       High School
           ...
4995    High School
4996        Unknown
4997    High School
4998     Bachelor's
4999            PhD
Name: Parent_Education_Level, Length: 5000, dtype: str

In [28]:
# Exercise 3
# EDA for column testing

In [29]:
# Exercise 4
# Discribtive statistics of testing column (count, mean, std)

In [30]:
# Exercise 5
# Calculate T-Statistic and P-Value
# significance level is 0.05
# Does High Stress Lead to Lower Performance?
alpha = 0.05

# Two groups based on stress level
high_stress = df[df['Stress_Level (1-10)'] >= 7]['Total_Score']
low_stress  = df[df['Stress_Level (1-10)'] <= 4]['Total_Score']

# Independent t-test
t_stat, p_value = stats.ttest_ind(high_stress, low_stress)

print(f"T-Statistic : {t_stat:.4f}")
print(f"P-Value     : {p_value:.4f}")
print(f"Alpha       : {alpha}")

if p_value < alpha:
    print("\nReject H₀ — High stress significantly lowers performance")
else:
    print("\nFail to reject H₀ — No significant difference")

T-Statistic : 0.5030
P-Value     : 0.6150
Alpha       : 0.05

Fail to reject H₀ — No significant difference

In [31]:
# Exercise 6
# Conclussion result